version: '3.8'

services:
  api:
    build: fraternodjango/.
    command: gunicorn fraternodjango.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./fraternodjango:/app
    expose:
      - "8000"
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=fraternodjango.settings

  # db:
  #   image: postgres:13
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html/static
      - ./fraternodjango/staticfiles:/usr/share/nginx/html/static/staticfiles
    ports:
      - "80:80"
    depends_on:
      - api
      - swagger-ui

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8001"
    volumes:
      - ./schema.yml:/schema.yml
    environment:
      - SWAGGER_JSON=/schema.yml

volumes:
  postgres_data:
